"""Self-contained shell completion generation from the argparse parser.

``mxtop --print-completion {bash,zsh,fish}`` emits a completion script on
stdout. Scripts are generated from the live parser, so new options appear
automatically; tests assert the round-trip stays complete.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass

from mxtop._compat import DATACLASS_SLOTS


@dataclass(**DATACLASS_SLOTS)
class _Option:
    strings: tuple[str, ...]
    help: str
    choices: tuple[str, ...]
    takes_value: bool


def _collect_options(parser: argparse.ArgumentParser) -> list[_Option]:
    options: list[_Option] = []
    for action in parser._actions:  # noqa: SLF001 - argparse has no public option list
        if not action.option_strings:
            continue
        takes_value = action.nargs != 0 and not isinstance(
            action,
            (
                argparse._StoreTrueAction,  # noqa: SLF001
                argparse._StoreFalseAction,  # noqa: SLF001
                argparse._CountAction,  # noqa: SLF001
                argparse._HelpAction,  # noqa: SLF001
                argparse._VersionAction,  # noqa: SLF001
            ),
        )
        first_help_line = (action.help or "").split("\n")[0]
        choices = tuple(str(choice) for choice in action.choices or ())
        # Ranges like the 1..99 threshold values are noise as completions.
        if len(choices) > 16:
            choices = ()
        options.append(
            _Option(
                strings=tuple(action.option_strings),
                help=first_help_line.replace("'", "'\\''"),
                choices=choices,
                takes_value=takes_value,
            )
        )
    return options


def _bash(options: list[_Option]) -> str:
    all_flags = " ".join(flag for option in options for flag in option.strings)
    value_cases = []
    for option in options:
        if option.choices:
            pattern = "|".join(option.strings)
            words = " ".join(option.choices)
            value_cases.append(
                f'        {pattern})\n'
                f'            COMPREPLY=( $(compgen -W "{words}" -- "$cur") )\n'
                f"            return 0\n"
                f"            ;;"
            )
    cases = "\n".join(value_cases)
    return f"""\
# bash completion for mxtop. Generated by `mxtop --print-completion bash`.
_mxtop() {{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    case "$prev" in
{cases}
    esac
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{all_flags}" -- "$cur") )
        return 0
    fi
}}
complete -F _mxtop mxtop
"""


def _zsh(options: list[_Option]) -> str:
    specs = []
    for option in options:
        value = ""
        if option.takes_value:
            value = f":value:({' '.join(option.choices)})" if option.choices else ":value:"
        for flag in option.strings:
            specs.append(f"        '{flag}[{option.help}]{value}'")
    body = " \\\n".join(specs)
    return f"""\
#compdef mxtop
# zsh completion for mxtop. Generated by `mxtop --print-completion zsh`.
_arguments -s \\
{body}
"""


def _fish(options: list[_Option]) -> str:
    lines = []
    for option in options:
        parts = ["complete -c mxtop"]
        for flag in option.strings:
            if flag.startswith("--"):
                parts.append(f"-l {flag[2:]}")
            elif len(flag) == 2:
                parts.append(f"-s {flag[1:]}")
            else:
                # fish has no native support for multi-char single-dash
                # flags like -ov; the long form still completes.
                continue
        if option.choices:
            parts.append(f"-x -a '{' '.join(option.choices)}'")
        elif option.takes_value:
            parts.append("-r")
        if option.help:
            parts.append(f"-d '{option.help}'")
        lines.append(" ".join(parts))
    body = "\n".join(lines)
    return f"""\
# fish completion for mxtop. Generated by `mxtop --print-completion fish`.
{body}
"""


def render_completion(parser: argparse.ArgumentParser, shell: str) -> str:
    options = _collect_options(parser)
    if shell == "bash":
        return _bash(options)
    if shell == "zsh":
        return _zsh(options)
    if shell == "fish":
        return _fish(options)
    raise ValueError(f"unsupported shell: {shell}")
